version: '3'
services:
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  redis:
    container_name: redis-backend
    image: "redis:alpine"