version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Identify << pipeline.project.git_url >>:<<pipeline.git.branch >>"
          command: "echo << pipeline.project.git_url >>:<<pipeline.git.branch >>"

      - run:
          name: "clone pm4core-docker"
          command: "git clone --depth 1 https://github.com/ProcessMaker/pm4core-docker.git -b v2 ."
      
      - restore_cache:
          keys:
            - build-cache
      
      - run:
          command: "mkdir -p cache"
          
      - run:
          name: "build the local cicd image and run tests"
          command: |
            source set_context_example.sh
            export GITHUB_TOKEN=$PM_GITHUB_TOKEN
            docker-compose run -e BUILD_JAVASCRIPT=false cicd

      - save_cache:
          key: build-cache
          paths:
            - cache

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
