version: 2.1

parameters:
  package_branch:
    type: string
    default: "null"
  package_url:
    type: string
    default: "null"
  sha:
    type: string
    default: "null"
  project:
    type: string
    default: "null"
  pull_req_id:
    type: string
    default: "null"
  body:
    type: string
    default: "null"

defaults: &defaults
  environment:
    TERM: xterm
    LC_ALL: en_US.UTF-8
  working_directory: ~/repo

jobs:
  job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: make script
          command: "echo 'echo \"Got body $CI_PR_BODY project: $CI_PROJECT branch: $CI_PACKAGE_BRANCH\"' > test.sh && chmod 755 test.sh"
      - run:
            name: 'build the local cicd image and run tests'
            command: |
              CI_PR_BODY="<<pipeline.parameters.body>>" \
              CI_PROJECT="<<pipeline.parameters.project>>" \
              CI_PACKAGE_BRANCH="<<pipeline.parameters.package_branch>>" \
              ./test.sh

# our single workflow, that triggers the setup job defined above
workflows:
  test:
    jobs:
      - job