version: 2.1

parameters:
  triggered_from:
    type: string
    default: "circleci ui"

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - run: # run a command
          name: Load config!
          command: curl https://gist.githubusercontent.com/nolanpro/85916008e6f2ee2f4487d903a41c3894/raw/config.yml --output core_config.yml
      - continuation/continue:
          configuration_path: core_config.yml # use newly generated config to continue

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup