# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  setup-docker:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          name: "clone pm4core-docker"
          command: "git clone --depth 1 https://github.com/ProcessMaker/pm4core-docker.git -b v2 $CIRCLE_WORKING_DIRECTORY"
      - run:
          name: "ls"
          command: pwd
      - run:
          name: "set up example context"
          command: source set_context_example.sh
      - run:
          name: "build the local cicd image and run tests"
          command: docker-compose run cicd

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - setup-docker
