name: test-workflows
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pm4core-docker
        uses: actions/checkout@v2
        with:
          repository: 'processmaker/pm4core-docker'
          ref: 'v2'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/cache
          key: pm4-build-cache-v1
      
      - name: test cache
        run: mkdir -p cache && echo "foo" > cache/test.txt
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # - name: Install
      #   run: docker-compose run build
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PM_GITHUB_TOKEN }}
      #     GITHUB_CONTEXT: ${{ toJSON(github.event.pull_request) }}
      
