name: test-workflows
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pm4core-docker
        uses: actions/checkout@v2
        with:
          repository: 'processmaker/pm4core-docker'
          ref: 'v2'

      # - name: Build
      #   run: docker-compose build build
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PM_GITHUB_TOKEN }}
      #     GITHUB_CONTEXT: ${{ toJSON(github.event.pull_request) }}

      - name: Install and run unit tests
        # run: docker-compose up --exit-code-from install install
        run: docker-compose up install
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
